### ISSUE TITLE
Daymet projection issue

### ISSUE THREAD

**Issue by apmonr** [ropensci/FedData#50]
I think I have found a problem with how the function get_daymet() is downloading and projecting Daymet data. To illustrate, below is code for downloading and summarizing precipitation data based on a spatial polygon. 

```
library(raster)
library(FedData)

coords <- data.frame(x =  c(-781513.3, -780784.5, -780206.5, -779610.9, -777519.2, -774070.9, -773398.9, 
                  -770236.2, -759515.7,  -756572.8, -753185.0, -750425.4, -750124.1, -743532.8, 
                  -743133.3, -742636.0, -742762.8, -743530.6, -743714.0, -740477.3, -726006.6, 
                  -723974.6, -726171.4, -726266.6, -726562.5, -730061.4, -733758.8, -735010.2, 
                  -722993.8, -708032.2, -703248.6, -703168.0, -688840.0, -627003.8, -604666.3, 
                  -607956.6, -598297.7, -593347.1, -583536.4, -578905.2, -891451.8, -890376.1, 
                  -889166.1, -894946.7, -896444.0, -895870.3, -900715.3, -900307.9, -886998.8,
                  -878487.5, -872325.6, -872112.7, -876478.8, -879681.1, -884088.0, -883934.3, 
                  -872404.4, -864362.5, -843583.6, -831356.8, -826167.2, -819254.8),
           y = c(131288.513, 120957.804, 115945.728, 112858.831, 106894.589, 98016.751,
                 97157.180, 93114.971, 84822.258, 77197.090, 73601.454, 68662.313, 65453.122, 
                 61006.704, 61027.829, 55529.371, 46723.450, 45345.035, 44452.053, 28121.394, 
                 14650.441, 6405.568, 2975.987, 2788.791, -3412.351, -17649.200, -23249.483, 
                 -24591.815, -41290.364, -58807.642, -61132.994, -61009.558, -72123.872, 
                 -82033.426, -87179.701, -95284.997, -99049.699, -105533.617, -124010.486, 
                 -133129.244, -110766.271, -106241.859, -104658.615, -93750.201, -92294.277, 
                 -77683.348, -72764.810, -46793.838, -40809.669, -39804.602, -25626.962, 
                 -24831.559, -20492.441, -16033.023, 8085.789, 8421.395, 55368.204, 57752.300, 
                 104532.769, 106515.735, 135119.201, 138758.535))

example <- SpatialPolygons(list(Polygons(list(Polygon(coords)), "1")))
crs(example) <- "+proj=lcc +lat_1=25 +lat_2=45 +lat_0=42.5 +lon_0=-100 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs" # Daymet data projection

trial_prcp <- get_daymet(template = example, label = "studyarea", 
                         elements = "prcp", year = 2017)

trial_prcp_sum <- sum(trial_prcp$prcp) # Annual prcp
raster::plot(trial_prcp_sum, main = "Total Precipitation")
raster::plot(example, add = TRUE)
```

![daymet_prcp_example](https://user-images.githubusercontent.com/6464068/78715941-5a841d00-78db-11ea-861c-cf2717600982.jpeg)

However, I believe the polygon is not overlapping the raster correctly. This becomes apparent when we download and examine another, different dataset, such as elevation:

```
example_ned <- spTransform(example, CRS = "+proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs")
trial_ned <- get_ned(template = example_ned, label = "studyarea")
raster::plot(trial_ned, main = “Elevation")
raster::plot(example_ned, add = TRUE)
```

![NED_example](https://user-images.githubusercontent.com/6464068/78715925-535d0f00-78db-11ea-9d3b-ddb921b28973.jpeg)

In the case of elevation, the border of the polygon correctly follows the mountain ridges in the north, whereas the polygon does not with the Daymet raster. I do not believe this error is unique to the FedData package as I have seen this discrepancy when I download and mosaic Netcdf data myself using the raster package. I also realize these datasets are in different projections but I do not see how that will lead to such differences, given the rasters and polygons are in the same projection. If anyone has any insights into this pattern, and how to correct it, I would be grateful. I am using R version 3.6.3, FedData version 2.5.7, and raster version 3.0-12.

Thank you for your time,
Adrian

**Comment by bocinsky** [comment]
Hi there. Yes, there is an issue with he projection of the Daymet data served through the THREDDS server from which we get the data. I've fixed the problem in the development version of FedData. I'm in the process of making other changes, though, so it is not yet on CRAN.

Install the development version like this:

```r
install.packages("devtools")
devtools::install_github("ropensci/FedData")
```

Let me know if that fixes your problem!

**Comment by apmonr** [comment]
Thanks for the quick response. I downloaded the development version on another computer (and fixed typos in the code above) but I am still seeing the same projection difference.

**Comment by bocinsky** [comment]
Can you check one more thing for me? Can you run it using the “force.redo=TRUE” parameter?

KB

**Comment by bocinsky** [comment]
Missed this:
> I downloaded the development version on another computer (and fixed typos in the code above) but I am still seeing the same projection difference.

I'll try and see what's up.

**Comment by apmonr** [comment]
Actually, I think I found it. The new raster is in a different projection (+proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0). Once I reproject the polygon, it works!

**Comment by bocinsky** [comment]
Ah! Well, good. Yes, the problem with the Daymet data was that the data weren’t actually in the projection it gets downloaded as. Glad things are looking correct. I’m gong to close this, but feel free to re-open if you keep having trouble.

**Comment by apmonr** [comment]
I had one more question, if you don't mind. Could you tell me how this new function differs from the previous version, to fix the projection issue? Thanks again,

Adrian

**Comment by bocinsky** [comment]
Yep. It's actually fairly substantially different. It now downloads data using a web coverage service (WCS) hosted by ORNL DAAC. However, the WCS was mislabeling the projection of the data; of the downloaded data. The data come in from the WCS labeled with projection "+proj=lcc +lon_0=-100 +lat_0=42.5 +x_0=0 +y_0=0 +lat_1=25 +a=6378137 +rf=298.257223563 +lat_2=45", when it should actually be "+proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs".

See [issue #49](https://github.com/ropensci/FedData/issues/49).

**Comment by apmonr** [comment]
Ah OK, I see now. It looks like this is a more widespread issue, as I found it reported for the daymetr package as well (https://github.com/khufkens/daymetr/issues/36).
